apiVersion: v1
kind: Service
metadata:
  name: micro-proxy
  namespace: default
  labels:
    micro: runtime
    name: proxy
    version: latest
spec:
  ports:
  - name: proxy
    port: 8081
    targetPort: 8081
  - name: proxy-grpc-web
    port: 8082
    targetPort: 8082
  selector:
    name: micro-proxy
    micro: runtime
    version: latest